### ISSUE TITLE
Authorization mechanism AWS4-HMAC-SHA256, eu-central-1 not supported?

### ISSUE THREAD

**Issue by JoseGM** [yegor256/s3auth#214]
Hi,

I'm having trouble using s3auth with a bucket hosted in Frankfurt (eu-central-1).

I get the following error when trying to get .htpasswd:

    java.io.IOException: failed to fetch /.htpasswd from 'mydomainname' (key=AK******): ["'.htpasswd': Status Code: 400, AWS Service: Amazon S3, AWS Request ID: ED253D48FDAE61D1, AWS Error Code: InvalidRequest, AWS Error Message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.", "'.htpasswd': Status Code: 400, AWS Service: Amazon S3, AWS Request ID: 202EB46CEDC68A5D, AWS Error Code: InvalidRequest 

Is this new region not supported yet?

Thanks in advance.

**Comment by davvd** [comment]
@jenya you're working with this ticket for the last 13 days. If it's not closed within the next 16 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -30 added to your rating, current score is: [-105](http://www.netbout.com/b/35092?open=rating)

**Comment by davvd** [comment]
@jenya the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html); -60 to your rating, your total score is [-375](http://www.netbout.com/b/35092?open=rating)

**Comment by davvd** [comment]
@dpisarenko please proceed, it's yours

**Comment by dpisarenko** [comment]
@JoseGM @yegor256 Is it possible that I get access to a S3 instance, on which this error occurs (i. e. first I write a simple program, which connects to S3 without getting the error, then I modify s3auth code and write tests) ?

**Comment by yegor256** [comment]
@dpisarenko I will create a test S3 bucket for you now and will send you access credentials in netbout

**Comment by dpisarenko** [comment]
It seems that the problem can be fixed by upgrading to `com.amazonaws:aws-java-sdk` version `1.9.14`.

Justification:

I upgraded the version and then ran the following test (`accessKey` and `secret` are set to those provided by @yegor256 ).

```
    @Test
    public void spike() {
        final String accessKey = "...";
        final String secret = "...";
        final AmazonS3 client = new AmazonS3Client(
            new BasicAWSCredentials(accessKey, secret),
            new ClientConfiguration()
                .withSocketTimeout(0)
                .withProtocol(Protocol.HTTP)
        );
        client.setRegion(com.amazonaws.regions.Region.getRegion(Regions.EU_CENTRAL_1 ));
        client.doesBucketExist("someBucket");
    }
```
I expected an error to occur at the line `client.doesBucketExist("someBucket");`, but it didn't.

Questions:

  1. @yegor256 @JoseGM Is it correct that the test above would have caused an authorization problem, if it existed in `com.amazonaws:aws-java-sdk` version `1.9.14` (is the test right) ?
  1. Can we change the version of `com.amazonaws:aws-java-sdk` to `1.9.14` in `pom.xml` of s3auth-hosts and add puzzles for 3 non-implemented methods (`com.s3auth.hosts.MkAmazonS3.enableRequesterPays`, `disableRequesterPays`, `isRequesterPaysEnabled` - they are necessary after upgrade to newer AWS SDK) ?

**Comment by yegor256** [comment]
@dpisarenko good catch. sure, go ahead and upgrade the AWS SDK. I don't think we need puzzles for that methods in `MkAmazonS3`. we don't use them, I guess. so just leave them unimplemented

**Comment by dpisarenko** [comment]
@yegor256 How can I disable checkstyle check for the max. number of methods in the class `MkAmazonS3` ? I tried to put `@checkstyle MethodCountCheck` into the Javadoc header of that class, but it didn't help.

**Comment by dpisarenko** [comment]
@JoseGM Now the changes are merged. Please check, if you can access the Frankfurt bucket now. If you can, please close the issue.

**Comment by yegor256** [comment]
@dpisarenko let me deploy it first

**Comment by yegor256** [comment]
@rultor deploy

**Comment by JoseGM** [comment]
@dpisarenko won't be able to test it for a while. I had to move my project to another region. If someone else can test it and it works, feel free to close the issue. Thanks!

**Comment by dpisarenko** [comment]
@yegor256 @davvd Can someone test whether the new version works with EU Central region?

**Comment by yegor256** [comment]
@dpisarenko you can test it yourself. you have an S3 bucket and an IAM user with a full access to it. register an account at www.s3auth.com, register a bucket there. your DNS name is dpisarenko.teamed.io (I pointed it already to `relay.s3auth.com`). and test :)

**Comment by dpisarenko** [comment]
@yegor256 I managed to create an account at s3auth.com (see http://i.imgur.com/wfQgCdP.png ). What should I do next to reproduce the bug, if it still exists?

**Comment by yegor256** [comment]
@dpisarenko you did it wrong. the domain name and bucket name should be `dpisarenko.teamed.io`. Delete this one and create another one. And they go with your browser to `http://dpisarenko.teamed.io`. And don't forget to put `.htpasswd` file into the bucket.

**Comment by dpisarenko** [comment]
@yegor256 Thanks. Now I see this: http://i.imgur.com/OuFlC8J.png . Does it mean the error is actually fixed?

**Comment by yegor256** [comment]
@dpisarenko yes, it looks like it's fixed. To be 100% sure, upload a sample `index.html` to the bucket and refresh the page.

**Comment by dpisarenko** [comment]
@yegor256 I uploaded `index.html` page with lettering `This is a test of the issue s3auth-214.`. Seems to work for me.

**Comment by yegor256** [comment]
@JoseGM I think this issue is fixed, since this URL works fine: http://dpisarenko.teamed.io/.htpasswd. The S3 bucket is hosted in Frankfurt. Please, close this issue

**Comment by JoseGM** [comment]
Looks good. Good job.

**Comment by davvd** [comment]
@dpisarenko Thanks for your contribution, **30 mins** was added to your account, payment ID is `50524332`

added +30 to your rating, now it is equal to [+325](http://www.netbout.com/b/35089?open=rating)

**Comment by lassebn** [comment]
I am experiencing this issue as well, with a new bucket hosted in Frankfurt. Can I do anything to fix this myself, or does s3auth need to be updated?

**Comment by yegor256** [comment]
@lassebn I think that you're having some other issue. This problem (with Frankfurt buckets) was fixed already. Please, create a new issue and explain the problem there, we'll try to help.

**Comment by jens876** [comment]
You have to define 's3-eu-central-1' as AWS S3 endpoint in the s3auth.com domain management. Then it works. With the 's3' endpoint the error still occurs.
